In [161]:
import numpy as np
import pandas as pd


np.random.seed(3)

In [116]:
#1.How likely is it that you roll doubles when rolling two dice?

n_rows = 10_000
n_cols = 2

rolls = np.random.choice(range(1,7), n_rows * n_cols).reshape(n_rows, n_cols)
df_rolls = pd.DataFrame(rolls)

In [117]:
df_rolls['success_fail'] = df_rolls[0] == df_rolls[1]

In [118]:
p_success = df_rolls.success_fail.mean()
p_success

0.1711

In [119]:
#2. If you flip 8 coins, 
n_rows = 10_000
n_cols = 8

#true for heads
flips = np.random.choice([True, False], n_rows * n_cols).reshape(n_rows, n_cols)
flips

array([[ True, False, False, ..., False,  True, False],
       [ True, False,  True, ..., False, False, False],
       [ True, False, False, ..., False,  True,  True],
       ...,
       [ True,  True, False, ...,  True,  True,  True],
       [ True, False,  True, ..., False,  True,  True],
       [ True, False,  True, ..., False,  True,  True]])

In [120]:
#2.a. what is the probability of getting exactly 3 heads?
p_3 = ((flips
           .sum(axis = 1) == 3)
           .mean())
p_3

0.214

In [121]:
#2.b. What is the probability of getting more than 3 heads?
p_3_or_more = ((flips
           .sum(axis = 1) > 3)
           .mean())
p_3_or_more

0.6384

In [122]:
#3. There are approximitely 3 web development cohorts for every 1 
#data science cohort at Codeup. Assuming that Codeup randomly selects
#an alumni to put on a billboard, what are the odds that the two 
#billboards I drive past both have data science students on them?
n_rows = 10_000
n_cols = 2

#true for student being in data science
board_has_ds = np.random.choice([True, False,False,False], n_rows * n_cols).reshape(n_rows, n_cols)
board_has_ds

array([[ True, False],
       [False, False],
       [False, False],
       ...,
       [ True, False],
       [False, False],
       [False,  True]])

In [123]:
p_2_ds = ((board_has_ds
           .sum(axis = 1) == 2)
           .mean())
p_2_ds

0.0662

In [136]:
#4. Codeup students buy, on average, 3 poptart packages (+- 1.5) a 
#day from the snack vending machine. If on monday the machine is 
#restocked with 17 poptart packages, how likely is it that I will be 
#able to buy some poptarts on Friday afternoon?
n_rows = 10_000
n_cols = 5

#generates random number of normal distribution with mu==3 and sigma==1.5
pops_bought = np.random.normal(3, 1.5, (n_rows, n_cols))
pops_bought = pops_bought.round(0)
pops_bought

array([[ 0.,  2.,  5.,  3.,  4.],
       [ 2.,  3.,  1.,  4.,  3.],
       [ 2.,  4.,  3.,  3., -1.],
       ...,
       [ 0.,  3.,  2.,  4.,  4.],
       [ 4.,  1.,  0.,  3.,  4.],
       [ 2.,  5.,  2.,  1., -0.]])

In [138]:
p_pops_left = ((pops_bought
           .sum(axis = 1) <= 16)
           .mean())
p_pops_left

0.6735

In [137]:
#zack's way to remove negs
pops_bought_no = np.where(pops_bought < 0, 0, pops_bought)
pops_bought_no

array([[ 0.,  2.,  5.,  3.,  4.],
       [ 2.,  3.,  1.,  4.,  3.],
       [ 2.,  4.,  3.,  3.,  0.],
       ...,
       [ 0.,  3.,  2.,  4.,  4.],
       [ 4.,  1.,  0.,  3.,  4.],
       [ 2.,  5.,  2.,  1., -0.]])

In [139]:
p_pops_left = ((pops_bought_no
           .sum(axis = 1) <= 16)
           .mean())
p_pops_left

0.6715

In [140]:
#Compare Heights
#Men have an average height of 178 cm and standard deviation of 8cm.
#Women have a mean of 170, sd = 6cm.
#If a man and woman are chosen at random, P(woman taller than man)?
n_rows = 1_000_000
avg_m = 178
sd_m = 8
avg_w = 170
sd_w = 6

height_m = np.random.normal(avg_m, sd_m, (n_rows, 1))
height_w = np.random.normal(avg_w, sd_w, (n_rows, 1))

heights = pd.DataFrame(height_m).rename(columns = {0:'height_m'})
heights['height_w'] = height_w
heights.head(5)

height_m    height_w
0  181.480229  177.756905
1  175.558624  174.680157
2  149.907453  159.024738
3  160.616646  160.595591
4  176.829214  165.772096

In [141]:
heights['taller_w'] = heights.height_w > heights.height_m
heights.head(5)

height_m    height_w  taller_w
0  181.480229  177.756905     False
1  175.558624  174.680157     False
2  149.907453  159.024738      True
3  160.616646  160.595591     False
4  176.829214  165.772096     False

In [142]:
heights.taller_w.mean()

0.210466

In [146]:
#zack's way with np arrays
(height_m < height_w).mean()

0.210466

In [157]:
#When installing anaconda on a student's computer, there's a 1 in 250 
#chance that the download is corrupted and the installation fails. 
#What are the odds that after having 50 students download anaconda, 
#no one has an installation issue? 100 students?
n_rows = 10_000
def conda_install_trials(trials):
    return np.random.choice(249 * [False]  + [True], (n_rows, trials))


In [156]:
#odds of no failures in 50 trials p(n == 0)
trials_50 = conda_install_trials(50)
(trials_50.sum(axis = 1) == 0).mean()

0.8125

In [150]:
#no failure in 100 trials p(n == 0)
trials_100 = conda_install_trials(100)
(trials_100.sum(axis = 1) == 0).mean()

0.6711

In [151]:
#1 or more issues in 150 trials p(n >= 1) or (1 - p(n == 0))
trials_150 = conda_install_trials(150)
1 - ((trials_150.
     sum(axis = 1) == 0)
     .mean())


0.45109999999999995

In [152]:
#no failures in 450 trials p(n == 0)
trials_450 = conda_install_trials(450)
((trials_450
    .sum(axis = 1) == 0)
    .mean())

0.1689

In [162]:
#There's a 70% chance on any given day that there will be at least 
#onefood truck at Travis Park. However, you haven't seen a food 
#truck there in 3 days. How unlikely is this? p(n == 3)

n_rows = 10_000
n_cols = 3

days = np.random.choice(7*[False] + 3*[True], (n_rows, n_cols))
days

array([[ True,  True, False],
       [ True,  True, False],
       [False, False,  True],
       ...,
       [False, False, False],
       [False, False, False],
       [False, False,  True]])

In [159]:
(days.sum(axis = 1) == 3).mean()

0.0259

In [169]:
#Jackie's way
lunches = np.random.choice(['food_truck','no_food_truck'], (n_rows,n_cols), p=[.7, 1-.7])
lunches

array([['food_truck', 'food_truck', 'food_truck'],
       ['no_food_truck', 'food_truck', 'food_truck'],
       ['food_truck', 'food_truck', 'food_truck'],
       ...,
       ['no_food_truck', 'food_truck', 'no_food_truck'],
       ['food_truck', 'no_food_truck', 'no_food_truck'],
       ['food_truck', 'food_truck', 'food_truck']], dtype='<U13')

In [171]:
(lunches == 'no_food_truck').all(axis = 1).mean()

0.0269

In [26]:
#How likely is it that a food truck will show up sometime this week? 
#1 - p(n == 7)
seven_days =  np.random.choice(7*[False] + 3*[True], (n_rows, 7))
seven_days

array([[ True, False,  True, ..., False,  True,  True],
       [False,  True,  True, ..., False, False,  True],
       [False, False, False, ..., False,  True, False],
       ...,
       [False,  True, False, ...,  True, False,  True],
       [False, False, False, ..., False, False,  True],
       [False,  True, False, ..., False,  True, False]])

In [27]:
p_seven_days = ((~seven_days).sum(axis = 1) > 0).mean()
p_seven_days 


0.9996

In [28]:
#If 23 people are in the same room, what are the odds that two of 
#them share a birthday? What if it's 20 people? 40?

In [176]:
def rand_birthdays(trials):
    return np.random.choice(range(365), (10_000, trials))

def percent_success(array):
    uniques = lambda x: len(set(x)) != len(x)
    success = np.array([uniques(trial) for trial in array]) 
    return success.mean()

In [173]:
people_23 = rand_birthdays(23)
percent_success(people_23)

0.5013

In [174]:
people_20 = rand_birthdays(20)
percent_success(people_20)

0.4106

In [175]:
people_40 = rand_birthdays(40)
percent_success(people_40)

0.8939