In [3]:
import numpy as np
import pandas as pd
np.random.seed(1313)

In [14]:
#1.How likely is it that you roll doubles when rolling two dice?

n_rows = 10_000
n_cols = 2

rolls = np.random.choice(range(1,7), n_rows * n_cols).reshape(n_rows, n_cols)
rolls = pd.DataFrame(rolls)

In [16]:
rolls['success_fail'] = rolls[0] == rolls[1]

In [61]:
p_success = rolls.success_fail.mean()
p_success

0.17

In [37]:
#2. If you flip 8 coins, 
n_rows = 10_000
n_cols = 8

#true for heads
flips = np.random.choice([True, False], n_rows * n_cols).reshape(n_rows, n_cols)
flips

array([[ True, False, False, ..., False, False,  True],
       [False, False,  True, ..., False,  True,  True],
       [False,  True, False, ..., False,  True, False],
       ...,
       [ True,  True,  True, ...,  True,  True,  True],
       [False,  True, False, ...,  True, False,  True],
       [False, False, False, ..., False, False,  True]])

In [38]:
#2.a. what is the probability of getting exactly 3 heads?
p_3 = ((flips
           .sum(axis = 1) == 3)
           .mean())
p_3

0.2228

In [39]:
#2.b. What is the probability of getting more than 3 heads?
p_3_or_more = ((flips
           .sum(axis = 1) > 3)
           .mean())
p_3_or_more

0.6343

In [44]:
#3. There are approximitely 3 web development cohorts for every 1 
#data science cohort at Codeup. Assuming that Codeup randomly selects
#an alumni to put on a billboard, what are the odds that the two 
#billboards I drive past both have data science students on them?
n_rows = 10_000
n_cols = 2

#true for student being in data science
board_has_ds = np.random.choice([True, False,False,False], n_rows * n_cols).reshape(n_rows, n_cols)
board_has_ds

array([[False, False],
       [False, False],
       [False, False],
       ...,
       [False,  True],
       [False, False],
       [False, False]])

In [45]:
p_2_ds = ((board_has_ds
           .sum(axis = 1) == 2)
           .mean())
p_2_ds

0.0672

In [59]:
#4. Codeup students buy, on average, 3 poptart packages (+- 1.5) a 
#day from the snack vending machine. If on monday the machine is 
#restocked with 17 poptart packages, how likely is it that I will be 
#able to buy some poptarts on Friday afternoon?
n_rows = 10_000
n_cols = 5

#generates random number of normal distribution with mu==3 and sigma==1.5
pops_bought = np.random.normal(3, 1.5, (n_rows, n_cols))
pops_bought.round(0)

array([[ 4.,  3.,  4.,  3.,  0.],
       [ 2.,  1.,  5.,  5.,  2.],
       [ 1.,  6.,  3.,  5.,  2.],
       ...,
       [ 4., -0.,  3.,  0.,  4.],
       [ 2.,  2.,  3.,  3.,  5.],
       [ 2.,  3.,  1.,  2.,  4.]])

In [60]:
p_pops_left = ((pops_bought
           .sum(axis = 1) <= 16)
           .mean())
p_pops_left

0.6274

In [79]:
#Compare Heights
#Men have an average height of 178 cm and standard deviation of 8cm.
#Women have a mean of 170, sd = 6cm.
#If a man and woman are chosen at random, P(woman taller than man)?
n_rows = 10_000
avg_m = 178
sd_m = 8
avg_w = 170
sd_w = 6

height_m = np.random.normal(avg_m, sd_m, (n_rows, 1))
height_w = np.random.normal(avg_w, sd_w, (n_rows, 1))

heights = pd.DataFrame(height_m).rename(columns = {0:'height_m'})
heights['height_w'] = height_w
heights.head(5)

height_m    height_w
0  167.793178  166.257740
1  185.221478  166.178120
2  187.591490  171.500993
3  175.598426  178.170466
4  189.312238  165.543346

In [80]:
heights['taller_w'] = heights.height_w > heights.height_m
heights.head(5)

height_m    height_w  taller_w
0  167.793178  166.257740     False
1  185.221478  166.178120     False
2  187.591490  171.500993     False
3  175.598426  178.170466      True
4  189.312238  165.543346     False

In [81]:
heights.taller_w.mean()

0.2142

In [106]:
#When installing anaconda on a student's computer, there's a 1 in 250 
#chance that the download is corrupted and the installation fails. 
#What are the odds that after having 50 students download anaconda, 
#no one has an installation issue? 100 students?
n_rows = 10_000
def conda_install_trials(trials):
    return np.random.choice([False] * 249 + [True], (n_rows, trials))


In [117]:
#odds of no failures in 50 trials p(n == 0)
trials_50 = conda_install_trials(50)
(trials_50.sum(axis = 1) == 0).mean()

0.8177

In [116]:
#no failure in 100 trials p(n == 0)
trials_100 = conda_install_trials(100)
(trials_100.sum(axis = 1) == 0).mean()

0.6731

In [125]:
#1 or more issues in 150 trials p(n >= 1) or (1 - p(n == 0))
trials_150 = conda_install_trials(150)
1 - ((trials_150.
     sum(axis = 1) == 0)
     .mean())


0.4607

In [127]:
#no failures in 450 trials p(n == 0)
trials_450 = conda_install_trials(450)
((trials_450
    .sum(axis = 1) == 0)
    .mean())

0.1602

In [133]:
#There's a 70% chance on any given day that there will be at least 
#onefood truck at Travis Park. However, you haven't seen a food 
#truck there in 3 days. How unlikely is this? p(n == 3)

n_rows = 10_000
n_cols = 3

days = np.random.choice(7*[False] + 3*[True], (n_rows, n_cols))
days

array([[False, False, False],
       [False,  True, False],
       [False,  True, False],
       ...,
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [134]:
(days.sum(axis = 1) == 3).mean()

0.0287

In [140]:
#How likely is it that a food truck will show up sometime this week? 
#1 - p(n == 7)
seven_days =  np.random.choice(7*[False] + 3*[True], (n_rows, 7))
seven_days

array([[ True, False, False, ..., False, False, False],
       [False, False,  True, ..., False, False,  True],
       [ True, False, False, ...,  True, False,  True],
       ...,
       [False,  True, False, ..., False, False, False],
       [ True,  True,  True, ..., False, False, False],
       [False,  True, False, ..., False, False,  True]])

In [165]:
p_seven_days = ((~seven_days).sum(axis = 1) > 0).mean()
p_seven_days 


0.9999

In [ ]:
#If 23 people are in the same room, what are the odds that two of 
#them share a birthday? What if it's 20 people? 40?

In [197]:
def rand_birthdays(trials):
    return np.random.choice(range(0,365), (1_000_000, trials))

def percent_success(array):
    successes = 0
    num_trials = len(array)
    for x in array:
        if len(x) != len(set(x)):
            successes += 1
    return successes/num_trials

In [198]:
people_23 = rand_birthdays(23)
percent_success(people_23)

0.507074

In [199]:
people_20 = rand_birthdays(20)
percent_success(people_20)

0.411192

In [200]:
people_40 = rand_birthdays(40)
percent_success(people_40)

0.891116